# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative "config/application"

Rails.application.load_tasks

# Add rswag rake tasks if available
begin
  require 'rswag/specs/rake_task'
  Rswag::Specs::RakeTask.new('rswag:specs:swaggerize')
rescue LoadError
  # rswag not available, skip
end
